# Generated by Django 5.2 on 2025-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_exchangeproposal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
