# Generated by Django 5.2 on 2025-04-08 16:24

import django.contrib.auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.contrib.auth.models.User, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
