# Generated by Django 5.2 on 2025-04-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_exchangeproposal_ad_receiver_and_more'),
        ('ads', '0008_alter_ad_user'),
    ]

    operations = [
    ]
