# Generated by Django 5.2 on 2025-08-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_delete_video_ad_title_video_ad_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='video_file',
            field=models.FileField(default='1111', upload_to='videos/', verbose_name='Видеофайл'),
        ),
    ]
