# Generated by Django 5.2 on 2025-08-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_alter_ad_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title_video',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Видеофайл'),
        ),
    ]
