# Generated by Django 5.2 on 2025-08-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_alter_ad_title_video_alter_ad_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title_video',
            field=models.CharField(default=123, max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='video_file',
            field=models.FileField(default=321, upload_to='videos/', verbose_name='Видеофайл'),
            preserve_default=False,
        ),
    ]
