# Generated by Django 5.2 on 2025-08-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_alter_ad_title_video_alter_ad_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(blank=True, default=123, upload_to='images/'),
            preserve_default=False,
        ),
    ]
