# Generated by Django 5.2 on 2025-08-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_alter_ad_image_url_alter_ad_title_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title_video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название video'),
        ),
    ]
