# Generated by Django 5.2 on 2025-08-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_alter_ad_title_video_alter_ad_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_audio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
