# Generated by Django 5.2 on 2025-08-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_ad_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views_audio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='views_image',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='views_video',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
