# Generated by Django 5.2 on 2025-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0024_ad_views_audio_ad_views_image_ad_views_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
