# Generated by Django 5.2 on 2025-08-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_alter_ad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
