# Generated by Django 5.2 on 2025-04-07 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 9, 24, 56, 912752, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
