# Generated by Django 5.2 on 2025-04-07 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_exchangeproposal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 9, 31, 56, 235689, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
