# Generated by Django 5.2 on 2025-04-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.IntegerField(),
        ),
    ]
