# Generated by Django 5.2 on 2025-08-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_alter_video_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='ad',
            name='title_video',
            field=models.CharField(default='title_video121212', max_length=200, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ad',
            name='video_file',
            field=models.FileField(default=None, upload_to='videos/', verbose_name='Видеофайл'),
        ),
    ]
