# Generated by Django 5.2 on 2025-08-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_alter_ad_title_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title_video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
