# Generated by Django 5.2 on 2025-08-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_ad_audio_file_ad_title_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
