# Generated by Django 5.2 on 2026-04-12 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0027_alter_ad_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time_operations', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата проведения операции')),
                ('operation_int', models.IntegerField(blank=True, null=True)),
                ('operation_model', models.IntegerField(blank=True, null=True)),
                ('balans', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
